name: Build Andr36oid and dArkOSRE
on:
  workflow_dispatch:
    inputs:
      pixeldrain_api_key:
        description: 'Pixeldrain API Key'
        required: false
        default: ''
      debug:
        description: 'debug'
        required: true
        default: 'false'
        type: choice
        options:
          - false
          - true

jobs:
  get_build_date:
    runs-on: ubuntu-latest
    outputs:
      build_datedash: ${{ steps.set_date.outputs.datedash }}
      build_date: ${{ steps.set_date.outputs.date }}
    steps:
      - name: Set build date
        id: set_date
        run:  |
          export datenow=$(TZ=America/New_York date +%Y-%m-%d-%H%M%S)
          echo "datedash=$(echo $datenow)" >> $GITHUB_OUTPUT
          echo "date=$(echo $datenow | sed 's|\-||g')" >> $GITHUB_OUTPUT

  build:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
    needs: get_build_date
    steps:
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: true
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: true
          swap-storage: true

      - uses: actions/checkout@v4

      - name: install Exfat
        run: sudo apt -y install exfatprogs

      - name: Build img
        run: |
          export BuildImgEnv=github
          export GH_build_date=${{ needs.get_build_date.outputs.build_date }}
          export NewOSList="andr36oid darkosre"
          chmod a+x ./buildimg.sh
          export ghdebug=${{ inputs.debug }}
          ./buildimg.sh $NewOSList
          df -h /

      - name: Release
        id: release
        uses: softprops/action-gh-release@v2
        with:
          files: R36S-Multiboot-*.img.xz.7z.*
          draft: true
          name: batch-andr36oid-darkosre-${{ needs.get_build_date.outputs.build_datedash }}
          tag_name: v-ad-${{ needs.get_build_date.outputs.build_date }}
          body: |
            # Custom Build: Andr36oid + dArkOSRE
            [Download Images Here](https://${{ github.repository_owner }}.github.io/R36S-Multiboot/)

      - name: Upload to Pixeldrain
        if: always() && inputs.pixeldrain_api_key != ''
        run: |
          for file in R36S-Multiboot-*.img.xz.7z.*; do
            if [ -f "$file" ]; then
              echo "Uploading $file to Pixeldrain..."
              curl -u ":${{ inputs.pixeldrain_api_key }}" -F "file=@$file" https://pixeldrain.com/api/file
            fi
          done
